language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
before_script:
  - bundle install
script:
  - rake test
notifications:
  emails:
    - awwa500@gmail.com
  on_success: always
  on_failure: always
